spring.application.name=lg-ecommerce
# database configuration

spring.datasource.url=jdbc:mysql://localhost:3306/lg_ecommerce
spring.datasource.username=root
spring.datasource.password=12345

#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true